apiVersion: v1
kind: ConfigMap
metadata:
  name: rds-configmap
data:
  USER: "root"
  DATABASE_URL: "mysql://k8s-desafio.cvhqofz3hgme.us-east-1.rds.amazonaws.com
:3306/k8s_desafio?useTimezone=true&serverTimezone=UTC"