apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java
  selector:
    matchLabels:
      app: java
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - image: didox/crud-java-login
        name: java-app
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: USER
          value: root
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: DATABASE_URL
        ports:
        - containerPort: 8080
      