apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  MYSQL_DATABASE: db_k8s_desafio
  DATABASE_URL: "mysql://mysql:3306/db_k8s_desafio?useTimezone=true&serverTimezone=UTC"
  USER: "k8s"