# Documentação 
# https://kubernetes.io/docs/concepts/storage/volumes/

### Criar o AWS EBS ###
# aws ec2 create-volume --availability-zone=us-east-1d --size=10 --volume-type=gp2
#############
# Pegar o ID do volume e configurar abaixo
#############

apiVersion: v1
kind: Pod
metadata:
  name: test-ebs
spec:
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /test-ebs
      name: test-volume
  volumes:
  - name: test-volume
    awsElasticBlockStore:
      volumeID: "<volume id>"
      fsType: ext4
