apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc-pod-didox-nodejs
spec:
  type: NodePort
  selector:
    app: label-pod-didox-nodejs
  ports:
    - port: 3000
      nodePort: 30001 #até 32767