apiVersion: v1
kind: Pod
metadata:
  name: didox-mysql
  labels:
    app: label-pod-didox-mysql
spec:
  volumes:
  # TODO - Ver aplicação do secret para varável de ambiente
  - name: secret-volume
    secret:
      secretName: db-mysql-secrets
  containers:
    - name: container-pod-mysql
      image: mysql:5.6
      ports:
        - containerPort: 3306
      env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: secret-volume
            key: MYSQL_ROOT_PASSWORD
      - name: MYSQL_DATABASE
        valueFrom:
          secretKeyRef:
            name: secret-volume
            key: MYSQL_DATABASE