- hosts:
  - k8s-master
  tasks:
    - name: "Configura hostname k8s-master"
      shell: hostname k8s-master && echo "k8s-master" > /etc/hostname
      become: yes
# ---
- hosts:
  - k8s-node-1
  tasks:
    - name: "Configura hostname k8s-node-1"
      shell: hostname k8s-node-1 && echo "k8s-node-1" > /etc/hostname
      become: yes
# ---
- hosts:
  - k8s-node-2
  tasks:
    - name: "Configura hostname k8s-node-2"
      shell: hostname k8s-node-2 && echo "k8s-node-2" > /etc/hostname
      become: yes
# ---
- hosts: all
  tasks:
    - name: install packages required by docker
      become: true
      apt:
        update_cache: yes
        state: latest
        name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gpg-agent
        - software-properties-common

    - name: add docker GPG key
      become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker apt repo
      become: true
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: install docker
      become: true
      apt:
        update_cache: yes
        state: latest
        name:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: "Corrigindo docker para o kubernetes"
      copy:
        src: "docker/daemon.json"
        dest: "/etc/docker/daemon.json"
      become: yes

    - name: "Restart docker"
      shell: sudo systemctl daemon-reload && sudo systemctl restart docker # && sudo systemctl restart kubelet
      become: yes

    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Add an apt signing key for Kubernetes
      become: true
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Adding apt repository for Kubernetes
      become: true
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list

    - name: Install Kubernetes binaries
      become: true
      apt: 
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - kubelet 
          - kubeadm 
          - kubectl

    - name: "Corrigindo containerd.conf"
      ignore_errors: yes
      copy:
        src: "containerd.conf"
        dest: "/etc/modules-load.d/containerd.conf"
      become: yes

    - name: "modprobe overlay"
      shell: modprobe overlay
      become: yes

    - name: "modprobe br_netfilter"
      shell: modprobe br_netfilter
      become: yes

    - name: "Corrigindo kubernetes.conf"
      ignore_errors: yes
      copy:
        src: "kubernetes.conf"
        dest: "/etc/sysctl.d/kubernetes.conf"
      become: yes

    - name: "sysctl --system"
      shell: sysctl --system
      become: yes

    - name: "modprobe overlay"
      shell: apt install -y curl gnupg2 software-properties-common apt-transport-https ca-certificates
      become: yes

    - name: "mkdir -p /etc/containerd"
      shell: mkdir -p /etc/containerd
      become: yes

    - name: "containerd config"
      shell: containerd config default > /etc/containerd/config.toml
      become: yes

    - name: "systemctl restart containerd"
      shell: systemctl restart containerd
      become: yes

    - name: Restart kubelet
      become: true
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted


# ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i hosts provisionar.yml -u ubuntu --private-key ~/Desktop/desafio_devops/chaves_desafio_kubernetes/id_rsa

