apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc-nodejs
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  externalIPs:
    - 181.72.121.1
  selector:
    app: lable-pod-nodejs